version: '3.4'

services:

  comfuzz_container_service:
    image: comfuzz_docker_compose_image:latest
    container_name: comfuzz_container
    depends_on:
      - "mysql_container_service"
    build:
      context: .
      dockerfile: ./Dockerfile
    # Keep container running
    tty: true
    restart: always
    privileged: true
    # network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    ports:
      - "12000:22"
    links:
      - mysql_container_service:comfuzz_mysql

  mysql_container_service:
    restart: always
    image: 17604768805/comfuzz_mysql
    container_name: comfuzz_mysql_container
    volumes:
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql123"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - "12001:3306"